//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В поле &apos;{0}&apos; введен не корректный email адрес.
        /// </summary>
        public static string EEmailError {
            get {
                return ResourceManager.GetString("EEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста выберите дату начала формирования справки.
        /// </summary>
        public static string EmptyFrom {
            get {
                return ResourceManager.GetString("EmptyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста выберите дату конца формирования справки.
        /// </summary>
        public static string EmptyTo {
            get {
                return ResourceManager.GetString("EmptyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обработке запроса произошла ошибка, детали ошибки доступны администратору в журнале событий..
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла непредвиденная ошибка.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ запрещен.
        /// </summary>
        public static string SAccessDanied {
            get {
                return ResourceManager.GetString("SAccessDanied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок 1.
        /// </summary>
        public static string SHeading1 {
            get {
                return ResourceManager.GetString("SHeading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок 2.
        /// </summary>
        public static string SHeading2 {
            get {
                return ResourceManager.GetString("SHeading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок 3.
        /// </summary>
        public static string SHeading3 {
            get {
                return ResourceManager.GetString("SHeading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок 4.
        /// </summary>
        public static string SHeading4 {
            get {
                return ResourceManager.GetString("SHeading4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок 5.
        /// </summary>
        public static string SHeading5 {
            get {
                return ResourceManager.GetString("SHeading5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок 6.
        /// </summary>
        public static string SHeading6 {
            get {
                return ResourceManager.GetString("SHeading6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставить файл (доступные форматы .rar, .zip, .doc, .docx, .xls, .xslx, .pdf, .ppt, .pptx, .mp4).
        /// </summary>
        public static string SInsertFile {
            get {
                return ResourceManager.GetString("SInsertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставить рисунок (доступные форматы .jpg, .jpeg, .png, .gif).
        /// </summary>
        public static string SInsertImage {
            get {
                return ResourceManager.GetString("SInsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интервал после {0} пкс.
        /// </summary>
        public static string SMarginBottom {
            get {
                return ResourceManager.GetString("SMarginBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интервал перед {0} пкс.
        /// </summary>
        public static string SMarginTop {
            get {
                return ResourceManager.GetString("SMarginTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню.
        /// </summary>
        public static string SMenu {
            get {
                return ResourceManager.GetString("SMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обычный текст.
        /// </summary>
        public static string SParagraph {
            get {
                return ResourceManager.GetString("SParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string SQuickSearch {
            get {
                return ResourceManager.GetString("SQuickSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цитата.
        /// </summary>
        public static string SQuotation {
            get {
                return ResourceManager.GetString("SQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуть ввод (Ctrl + Y).
        /// </summary>
        public static string SRedo {
            get {
                return ResourceManager.GetString("SRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string SSave {
            get {
                return ResourceManager.GetString("SSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АИС «Валютный контроль».
        /// </summary>
        public static string SSystemName {
            get {
                return ResourceManager.GetString("SSystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить ввод (Ctrl + Z).
        /// </summary>
        public static string SUndo {
            get {
                return ResourceManager.GetString("SUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь: .
        /// </summary>
        public static string SUser {
            get {
                return ResourceManager.GetString("SUser", resourceCulture);
            }
        }
    }
}
