//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionaries.Areas.DIC.GeneratedResources {
    using global::System;
    using global::System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BG_PaymentsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal BG_PaymentsResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dictionaries.Areas.DIC.GeneratedResources.BG_PaymentsResources", typeof(BG_PaymentsResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Платежи БГ.
        /// </summary>
        public static string BG_Payments__Title {
            get {
                return ResourceManager.GetString("BG_Payments__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Платежи БГ.
        /// </summary>
        public static string BG_Payments__Comment
        {
            get 
            {
                return ResourceManager.GetString("BG_Payments__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string BG_Payments__DescriptionRtf
        {
            get 
            {
                return ResourceManager.GetString("BG_Payments__DescriptionRtf", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Идентификатор.
        /// </summary>
        public static string id__Title {
            get {
                return ResourceManager.GetString("id__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Идентификатор.
        /// </summary>
        public static string id__Comment
        {
            get 
            {
                return ResourceManager.GetString("id__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сумма платежа.
        /// </summary>
        public static string Amount__Title {
            get {
                return ResourceManager.GetString("Amount__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сумма платежа.
        /// </summary>
        public static string Amount__Comment
        {
            get 
            {
                return ResourceManager.GetString("Amount__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Отправитель.
        /// </summary>
        public static string Sender__Title {
            get {
                return ResourceManager.GetString("Sender__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Отправитель.
        /// </summary>
        public static string Sender__Comment
        {
            get 
            {
                return ResourceManager.GetString("Sender__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Примечание.
        /// </summary>
        public static string Note__Title {
            get {
                return ResourceManager.GetString("Note__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Примечание.
        /// </summary>
        public static string Note__Comment
        {
            get 
            {
                return ResourceManager.GetString("Note__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Платежи БГ.
        /// </summary>
        public static string BG_Payments__VMTitle {
            get {
                return ResourceManager.GetString("BG_Payments__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Платежи БГ.
        /// </summary>
        public static string BG_Payments__VMComment
        {
            get 
            {
                return ResourceManager.GetString("BG_Payments__VMComment", resourceCulture);
            }
        }
    }
}