//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionaries.Areas.DIC.GeneratedResources {
    using global::System;
    using global::System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class bookForDataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal bookForDataResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dictionaries.Areas.DIC.GeneratedResources.bookForDataResources", typeof(bookForDataResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Книга для сбора данных.
        /// </summary>
        public static string bookForData__Title {
            get {
                return ResourceManager.GetString("bookForData__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Книга для сбора данных.
        /// </summary>
        public static string bookForData__Comment
        {
            get 
            {
                return ResourceManager.GetString("bookForData__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string bookForData__DescriptionRtf
        {
            get 
            {
                return ResourceManager.GetString("bookForData__DescriptionRtf", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to recId.
        /// </summary>
        public static string id__Title {
            get {
                return ResourceManager.GetString("id__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to recId.
        /// </summary>
        public static string id__Comment
        {
            get 
            {
                return ResourceManager.GetString("id__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to REFmsgQueId.
        /// </summary>
        public static string REFmsgQueId__Title {
            get {
                return ResourceManager.GetString("REFmsgQueId__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to REFmsgQueId.
        /// </summary>
        public static string REFmsgQueId__Comment
        {
            get 
            {
                return ResourceManager.GetString("REFmsgQueId__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to REFmsgId.
        /// </summary>
        public static string REFid__Title {
            get {
                return ResourceManager.GetString("REFid__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to REFmsgId.
        /// </summary>
        public static string REFid__Comment
        {
            get 
            {
                return ResourceManager.GetString("REFid__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to stmpBody.
        /// </summary>
        public static string stmpBody__Title {
            get {
                return ResourceManager.GetString("stmpBody__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to stmpBody.
        /// </summary>
        public static string stmpBody__Comment
        {
            get 
            {
                return ResourceManager.GetString("stmpBody__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to stmpDataType.
        /// </summary>
        public static string stmpDataType__Title {
            get {
                return ResourceManager.GetString("stmpDataType__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to stmpDataType.
        /// </summary>
        public static string stmpDataType__Comment
        {
            get 
            {
                return ResourceManager.GetString("stmpDataType__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to REFrxcId.
        /// </summary>
        public static string REFrxcId__Title {
            get {
                return ResourceManager.GetString("REFrxcId__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to REFrxcId.
        /// </summary>
        public static string REFrxcId__Comment
        {
            get 
            {
                return ResourceManager.GetString("REFrxcId__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Книга для сбора данных.
        /// </summary>
        public static string bookForData__VMTitle {
            get {
                return ResourceManager.GetString("bookForData__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Книга для сбора данных.
        /// </summary>
        public static string bookForData__VMComment
        {
            get 
            {
                return ResourceManager.GetString("bookForData__VMComment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Книга для сбора данных.
        /// </summary>
        public static string bookForDataMinimal__VMTitle {
            get {
                return ResourceManager.GetString("bookForDataMinimal__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Книга для сбора данных.
        /// </summary>
        public static string bookForDataMinimal__VMComment
        {
            get 
            {
                return ResourceManager.GetString("bookForDataMinimal__VMComment", resourceCulture);
            }
        }
    }
}