//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionaries.Areas.DIC.GeneratedResources {
    using global::System;
    using global::System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class isoMsgResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal isoMsgResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dictionaries.Areas.DIC.GeneratedResources.isoMsgResources", typeof(isoMsgResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string isoMsg__Title {
            get {
                return ResourceManager.GetString("isoMsg__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string isoMsg__Comment
        {
            get 
            {
                return ResourceManager.GetString("isoMsg__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string isoMsg__DescriptionRtf
        {
            get 
            {
                return ResourceManager.GetString("isoMsg__DescriptionRtf", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to msgId.
        /// </summary>
        public static string id__Title {
            get {
                return ResourceManager.GetString("id__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to msgId.
        /// </summary>
        public static string id__Comment
        {
            get 
            {
                return ResourceManager.GetString("id__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Владелец.
        /// </summary>
        public static string REFusrId__Title {
            get {
                return ResourceManager.GetString("REFusrId__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Владелец.
        /// </summary>
        public static string REFusrId__Comment
        {
            get 
            {
                return ResourceManager.GetString("REFusrId__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to parentMsgId.
        /// </summary>
        public static string parentMsgId__Title {
            get {
                return ResourceManager.GetString("parentMsgId__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to parentMsgId.
        /// </summary>
        public static string parentMsgId__Comment
        {
            get 
            {
                return ResourceManager.GetString("parentMsgId__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to bizMSGId.
        /// </summary>
        public static string bizId__Title {
            get {
                return ResourceManager.GetString("bizId__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to bizMSGId.
        /// </summary>
        public static string bizId__Comment
        {
            get 
            {
                return ResourceManager.GetString("bizId__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to grpMsgId.
        /// </summary>
        public static string grpMsgId__Title {
            get {
                return ResourceManager.GetString("grpMsgId__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to grpMsgId.
        /// </summary>
        public static string grpMsgId__Comment
        {
            get 
            {
                return ResourceManager.GetString("grpMsgId__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Тип платежа.
        /// </summary>
        public static string msgPurpose__Title {
            get {
                return ResourceManager.GetString("msgPurpose__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Тип платежа.
        /// </summary>
        public static string msgPurpose__Comment
        {
            get 
            {
                return ResourceManager.GetString("msgPurpose__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Направление.
        /// </summary>
        public static string msgDir__Title {
            get {
                return ResourceManager.GetString("msgDir__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Направление.
        /// </summary>
        public static string msgDir__Comment
        {
            get 
            {
                return ResourceManager.GetString("msgDir__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Тип МХ.
        /// </summary>
        public static string msgType__Title {
            get {
                return ResourceManager.GetString("msgType__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Тип МХ.
        /// </summary>
        public static string msgType__Comment
        {
            get 
            {
                return ResourceManager.GetString("msgType__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to msgTypeVer.
        /// </summary>
        public static string msgTypeVer__Title {
            get {
                return ResourceManager.GetString("msgTypeVer__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to msgTypeVer.
        /// </summary>
        public static string msgTypeVer__Comment
        {
            get 
            {
                return ResourceManager.GetString("msgTypeVer__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to msgError.
        /// </summary>
        public static string msgError__Title {
            get {
                return ResourceManager.GetString("msgError__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to msgError.
        /// </summary>
        public static string msgError__Comment
        {
            get 
            {
                return ResourceManager.GetString("msgError__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to state.
        /// </summary>
        public static string state__Title {
            get {
                return ResourceManager.GetString("state__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to state.
        /// </summary>
        public static string state__Comment
        {
            get 
            {
                return ResourceManager.GetString("state__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Системная дата импорта.
        /// </summary>
        public static string sysDate__Title {
            get {
                return ResourceManager.GetString("sysDate__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Системная дата импорта.
        /// </summary>
        public static string sysDate__Comment
        {
            get 
            {
                return ResourceManager.GetString("sysDate__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Системное время импорта.
        /// </summary>
        public static string sysTm__Title {
            get {
                return ResourceManager.GetString("sysTm__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Системное время импорта.
        /// </summary>
        public static string sysTm__Comment
        {
            get 
            {
                return ResourceManager.GetString("sysTm__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to sender.
        /// </summary>
        public static string sender__Title {
            get {
                return ResourceManager.GetString("sender__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to sender.
        /// </summary>
        public static string sender__Comment
        {
            get 
            {
                return ResourceManager.GetString("sender__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to addressee.
        /// </summary>
        public static string addressee__Title {
            get {
                return ResourceManager.GetString("addressee__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to addressee.
        /// </summary>
        public static string addressee__Comment
        {
            get 
            {
                return ResourceManager.GetString("addressee__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to rootTag.
        /// </summary>
        public static string rootTag__Title {
            get {
                return ResourceManager.GetString("rootTag__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to rootTag.
        /// </summary>
        public static string rootTag__Comment
        {
            get 
            {
                return ResourceManager.GetString("rootTag__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to stmp.
        /// </summary>
        public static string stmp__Title {
            get {
                return ResourceManager.GetString("stmp__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to stmp.
        /// </summary>
        public static string stmp__Comment
        {
            get 
            {
                return ResourceManager.GetString("stmp__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Источник.
        /// </summary>
        public static string stmpApp__Title {
            get {
                return ResourceManager.GetString("stmpApp__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Источник.
        /// </summary>
        public static string stmpApp__Comment
        {
            get 
            {
                return ResourceManager.GetString("stmpApp__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to sprtry.
        /// </summary>
        public static string sprtry__Title {
            get {
                return ResourceManager.GetString("sprtry__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to sprtry.
        /// </summary>
        public static string sprtry__Comment
        {
            get 
            {
                return ResourceManager.GetString("sprtry__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to aprtry.
        /// </summary>
        public static string aprtry__Title {
            get {
                return ResourceManager.GetString("aprtry__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to aprtry.
        /// </summary>
        public static string aprtry__Comment
        {
            get 
            {
                return ResourceManager.GetString("aprtry__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to mprty.
        /// </summary>
        public static string mprty__Title {
            get {
                return ResourceManager.GetString("mprty__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to mprty.
        /// </summary>
        public static string mprty__Comment
        {
            get 
            {
                return ResourceManager.GetString("mprty__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to mdate.
        /// </summary>
        public static string mdate__Title {
            get {
                return ResourceManager.GetString("mdate__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to mdate.
        /// </summary>
        public static string mdate__Comment
        {
            get 
            {
                return ResourceManager.GetString("mdate__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to swtMsg.
        /// </summary>
        public static string swtMsg__Title {
            get {
                return ResourceManager.GetString("swtMsg__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to swtMsg.
        /// </summary>
        public static string swtMsg__Comment
        {
            get 
            {
                return ResourceManager.GetString("swtMsg__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to isVolpay.
        /// </summary>
        public static string isVolpay__Title {
            get {
                return ResourceManager.GetString("isVolpay__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to isVolpay.
        /// </summary>
        public static string isVolpay__Comment
        {
            get 
            {
                return ResourceManager.GetString("isVolpay__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Да.
        /// </summary>
        public static string isVolpay__TrueText
        {
            get 
            {
                return ResourceManager.GetString("isVolpay__TrueText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Нет.
        /// </summary>
        public static string isVolpay__FalseText
        {
            get 
            {
                return ResourceManager.GetString("isVolpay__FalseText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to msgAmount.
        /// </summary>
        public static string msgAmount__Title {
            get {
                return ResourceManager.GetString("msgAmount__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to msgAmount.
        /// </summary>
        public static string msgAmount__Comment
        {
            get 
            {
                return ResourceManager.GetString("msgAmount__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Платежная система.
        /// </summary>
        public static string msgTerminal__Title {
            get {
                return ResourceManager.GetString("msgTerminal__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Платежная система.
        /// </summary>
        public static string msgTerminal__Comment
        {
            get 
            {
                return ResourceManager.GetString("msgTerminal__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to rsPrt.
        /// </summary>
        public static string rsPrt__Title {
            get {
                return ResourceManager.GetString("rsPrt__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to rsPrt.
        /// </summary>
        public static string rsPrt__Comment
        {
            get 
            {
                return ResourceManager.GetString("rsPrt__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to oprDate.
        /// </summary>
        public static string oprDate__Title {
            get {
                return ResourceManager.GetString("oprDate__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to oprDate.
        /// </summary>
        public static string oprDate__Comment
        {
            get 
            {
                return ResourceManager.GetString("oprDate__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to msgComment.
        /// </summary>
        public static string msgComment__Title {
            get {
                return ResourceManager.GetString("msgComment__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to msgComment.
        /// </summary>
        public static string msgComment__Comment
        {
            get 
            {
                return ResourceManager.GetString("msgComment__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string isoMsg__VMTitle {
            get {
                return ResourceManager.GetString("isoMsg__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string isoMsg__VMComment
        {
            get 
            {
                return ResourceManager.GetString("isoMsg__VMComment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string isoMsgMinimal__VMTitle {
            get {
                return ResourceManager.GetString("isoMsgMinimal__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string isoMsgMinimal__VMComment
        {
            get 
            {
                return ResourceManager.GetString("isoMsgMinimal__VMComment", resourceCulture);
            }
        }
    }
}