//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionaries.Areas.DIC.GeneratedResources {
    using global::System;
    using global::System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class isoPaymentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal isoPaymentResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dictionaries.Areas.DIC.GeneratedResources.isoPaymentResources", typeof(isoPaymentResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Платеж.
        /// </summary>
        public static string isoPayment__Title {
            get {
                return ResourceManager.GetString("isoPayment__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Платеж.
        /// </summary>
        public static string isoPayment__Comment
        {
            get 
            {
                return ResourceManager.GetString("isoPayment__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string isoPayment__DescriptionRtf
        {
            get 
            {
                return ResourceManager.GetString("isoPayment__DescriptionRtf", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to payId.
        /// </summary>
        public static string id__Title {
            get {
                return ResourceManager.GetString("id__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to payId.
        /// </summary>
        public static string id__Comment
        {
            get 
            {
                return ResourceManager.GetString("id__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to REFmsgId.
        /// </summary>
        public static string REFid__Title {
            get {
                return ResourceManager.GetString("REFid__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to REFmsgId.
        /// </summary>
        public static string REFid__Comment
        {
            get 
            {
                return ResourceManager.GetString("REFid__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Статус сообщение платежа.
        /// </summary>
        public static string state__Title {
            get {
                return ResourceManager.GetString("state__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Статус сообщение платежа.
        /// </summary>
        public static string state__Comment
        {
            get 
            {
                return ResourceManager.GetString("state__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to isBreaked.
        /// </summary>
        public static string isBreaked__Title {
            get {
                return ResourceManager.GetString("isBreaked__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to isBreaked.
        /// </summary>
        public static string isBreaked__Comment
        {
            get 
            {
                return ResourceManager.GetString("isBreaked__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Да.
        /// </summary>
        public static string isBreaked__TrueText
        {
            get 
            {
                return ResourceManager.GetString("isBreaked__TrueText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Нет.
        /// </summary>
        public static string isBreaked__FalseText
        {
            get 
            {
                return ResourceManager.GetString("isBreaked__FalseText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to grpMsgId.
        /// </summary>
        public static string grpMsgId__Title {
            get {
                return ResourceManager.GetString("grpMsgId__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to grpMsgId.
        /// </summary>
        public static string grpMsgId__Comment
        {
            get 
            {
                return ResourceManager.GetString("grpMsgId__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to txnId.
        /// </summary>
        public static string txnId__Title {
            get {
                return ResourceManager.GetString("txnId__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to txnId.
        /// </summary>
        public static string txnId__Comment
        {
            get 
            {
                return ResourceManager.GetString("txnId__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to endToEndId.
        /// </summary>
        public static string endToEndId__Title {
            get {
                return ResourceManager.GetString("endToEndId__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to endToEndId.
        /// </summary>
        public static string endToEndId__Comment
        {
            get 
            {
                return ResourceManager.GetString("endToEndId__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to uetrId.
        /// </summary>
        public static string uetrId__Title {
            get {
                return ResourceManager.GetString("uetrId__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to uetrId.
        /// </summary>
        public static string uetrId__Comment
        {
            get 
            {
                return ResourceManager.GetString("uetrId__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Время создания платежа.
        /// </summary>
        public static string grpCreDtTm__Title {
            get {
                return ResourceManager.GetString("grpCreDtTm__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Время создания платежа.
        /// </summary>
        public static string grpCreDtTm__Comment
        {
            get 
            {
                return ResourceManager.GetString("grpCreDtTm__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BatchBook.
        /// </summary>
        public static string grpBtchBookg__Title {
            get {
                return ResourceManager.GetString("grpBtchBookg__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BatchBook.
        /// </summary>
        public static string grpBtchBookg__Comment
        {
            get 
            {
                return ResourceManager.GetString("grpBtchBookg__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Вложенных платежей.
        /// </summary>
        public static string grpNbOfTxs__Title {
            get {
                return ResourceManager.GetString("grpNbOfTxs__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Вложенных платежей.
        /// </summary>
        public static string grpNbOfTxs__Comment
        {
            get 
            {
                return ResourceManager.GetString("grpNbOfTxs__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сумма.
        /// </summary>
        public static string grpTtlIntrBkSttlmAmt__Title {
            get {
                return ResourceManager.GetString("grpTtlIntrBkSttlmAmt__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сумма.
        /// </summary>
        public static string grpTtlIntrBkSttlmAmt__Comment
        {
            get 
            {
                return ResourceManager.GetString("grpTtlIntrBkSttlmAmt__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Ссу.
        /// </summary>
        public static string ccy__Title {
            get {
                return ResourceManager.GetString("ccy__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Ссу.
        /// </summary>
        public static string ccy__Comment
        {
            get 
            {
                return ResourceManager.GetString("ccy__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Операционная дата платежа.
        /// </summary>
        public static string grpDate__Title {
            get {
                return ResourceManager.GetString("grpDate__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Операционная дата платежа.
        /// </summary>
        public static string grpDate__Comment
        {
            get 
            {
                return ResourceManager.GetString("grpDate__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to grpSender.
        /// </summary>
        public static string grpSender__Title {
            get {
                return ResourceManager.GetString("grpSender__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to grpSender.
        /// </summary>
        public static string grpSender__Comment
        {
            get 
            {
                return ResourceManager.GetString("grpSender__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to grpAddressee.
        /// </summary>
        public static string grpAddressee__Title {
            get {
                return ResourceManager.GetString("grpAddressee__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to grpAddressee.
        /// </summary>
        public static string grpAddressee__Comment
        {
            get 
            {
                return ResourceManager.GetString("grpAddressee__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Комиссия.
        /// </summary>
        public static string chrgBr__Title {
            get {
                return ResourceManager.GetString("chrgBr__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Комиссия.
        /// </summary>
        public static string chrgBr__Comment
        {
            get 
            {
                return ResourceManager.GetString("chrgBr__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Наименование отправителя.
        /// </summary>
        public static string dbtrNm__Title {
            get {
                return ResourceManager.GetString("dbtrNm__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Наименование отправителя.
        /// </summary>
        public static string dbtrNm__Comment
        {
            get 
            {
                return ResourceManager.GetString("dbtrNm__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сектор экономики отправителя.
        /// </summary>
        public static string dbtrSeco__Title {
            get {
                return ResourceManager.GetString("dbtrSeco__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сектор экономики отправителя.
        /// </summary>
        public static string dbtrSeco__Comment
        {
            get 
            {
                return ResourceManager.GetString("dbtrSeco__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Резиденство отправителя.
        /// </summary>
        public static string dbtrIrs__Title {
            get {
                return ResourceManager.GetString("dbtrIrs__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Резиденство отправителя.
        /// </summary>
        public static string dbtrIrs__Comment
        {
            get 
            {
                return ResourceManager.GetString("dbtrIrs__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Главный бухгалтер отправителя.
        /// </summary>
        public static string dbtrAccountant__Title {
            get {
                return ResourceManager.GetString("dbtrAccountant__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Главный бухгалтер отправителя.
        /// </summary>
        public static string dbtrAccountant__Comment
        {
            get 
            {
                return ResourceManager.GetString("dbtrAccountant__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Руководитель отправителя.
        /// </summary>
        public static string dbtrHead__Title {
            get {
                return ResourceManager.GetString("dbtrHead__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Руководитель отправителя.
        /// </summary>
        public static string dbtrHead__Comment
        {
            get 
            {
                return ResourceManager.GetString("dbtrHead__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to ИИН, БИН отправителя.
        /// </summary>
        public static string dbtrIdn__Title {
            get {
                return ResourceManager.GetString("dbtrIdn__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to ИИН, БИН отправителя.
        /// </summary>
        public static string dbtrIdn__Comment
        {
            get 
            {
                return ResourceManager.GetString("dbtrIdn__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Страна резиденства отправителя.
        /// </summary>
        public static string dbtrCtryOfRes__Title {
            get {
                return ResourceManager.GetString("dbtrCtryOfRes__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Страна резиденства отправителя.
        /// </summary>
        public static string dbtrCtryOfRes__Comment
        {
            get 
            {
                return ResourceManager.GetString("dbtrCtryOfRes__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Счет отправителя.
        /// </summary>
        public static string dbtrAcct__Title {
            get {
                return ResourceManager.GetString("dbtrAcct__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Счет отправителя.
        /// </summary>
        public static string dbtrAcct__Comment
        {
            get 
            {
                return ResourceManager.GetString("dbtrAcct__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Бик отправителя.
        /// </summary>
        public static string dbtrAgt__Title {
            get {
                return ResourceManager.GetString("dbtrAgt__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Бик отправителя.
        /// </summary>
        public static string dbtrAgt__Comment
        {
            get 
            {
                return ResourceManager.GetString("dbtrAgt__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to отправитель.
        /// </summary>
        public static string dbtr__Title {
            get {
                return ResourceManager.GetString("dbtr__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to отправитель.
        /// </summary>
        public static string dbtr__Comment
        {
            get 
            {
                return ResourceManager.GetString("dbtr__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to получатель.
        /// </summary>
        public static string cdtr__Title {
            get {
                return ResourceManager.GetString("cdtr__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to получатель.
        /// </summary>
        public static string cdtr__Comment
        {
            get 
            {
                return ResourceManager.GetString("cdtr__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Наименование получателя.
        /// </summary>
        public static string cdtrNm__Title {
            get {
                return ResourceManager.GetString("cdtrNm__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Наименование получателя.
        /// </summary>
        public static string cdtrNm__Comment
        {
            get 
            {
                return ResourceManager.GetString("cdtrNm__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сектор экономики получателя.
        /// </summary>
        public static string cdtrSeco__Title {
            get {
                return ResourceManager.GetString("cdtrSeco__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сектор экономики получателя.
        /// </summary>
        public static string cdtrSeco__Comment
        {
            get 
            {
                return ResourceManager.GetString("cdtrSeco__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Резиденство получателя.
        /// </summary>
        public static string cdtrIrs__Title {
            get {
                return ResourceManager.GetString("cdtrIrs__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Резиденство получателя.
        /// </summary>
        public static string cdtrIrs__Comment
        {
            get 
            {
                return ResourceManager.GetString("cdtrIrs__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Главный бухгалтер получателя.
        /// </summary>
        public static string cdtrAccountant__Title {
            get {
                return ResourceManager.GetString("cdtrAccountant__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Главный бухгалтер получателя.
        /// </summary>
        public static string cdtrAccountant__Comment
        {
            get 
            {
                return ResourceManager.GetString("cdtrAccountant__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Руководитель получателя.
        /// </summary>
        public static string cdtrHead__Title {
            get {
                return ResourceManager.GetString("cdtrHead__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Руководитель получателя.
        /// </summary>
        public static string cdtrHead__Comment
        {
            get 
            {
                return ResourceManager.GetString("cdtrHead__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to ИИН, БИН получателя.
        /// </summary>
        public static string cdtrIdn__Title {
            get {
                return ResourceManager.GetString("cdtrIdn__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to ИИН, БИН получателя.
        /// </summary>
        public static string cdtrIdn__Comment
        {
            get 
            {
                return ResourceManager.GetString("cdtrIdn__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Страна резиденства получателя.
        /// </summary>
        public static string cdtrCtryOfRes__Title {
            get {
                return ResourceManager.GetString("cdtrCtryOfRes__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Страна резиденства получателя.
        /// </summary>
        public static string cdtrCtryOfRes__Comment
        {
            get 
            {
                return ResourceManager.GetString("cdtrCtryOfRes__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Счет получателя.
        /// </summary>
        public static string cdtrAcct__Title {
            get {
                return ResourceManager.GetString("cdtrAcct__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Счет получателя.
        /// </summary>
        public static string cdtrAcct__Comment
        {
            get 
            {
                return ResourceManager.GetString("cdtrAcct__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Бик получателя.
        /// </summary>
        public static string cdtrAgt__Title {
            get {
                return ResourceManager.GetString("cdtrAgt__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Бик получателя.
        /// </summary>
        public static string cdtrAgt__Comment
        {
            get 
            {
                return ResourceManager.GetString("cdtrAgt__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to cdtrAgtAcct.
        /// </summary>
        public static string cdtrAgtAcct__Title {
            get {
                return ResourceManager.GetString("cdtrAgtAcct__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to cdtrAgtAcct.
        /// </summary>
        public static string cdtrAgtAcct__Comment
        {
            get 
            {
                return ResourceManager.GetString("cdtrAgtAcct__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to cdtrAgtAcctTp.
        /// </summary>
        public static string cdtrAgtAcctTp__Title {
            get {
                return ResourceManager.GetString("cdtrAgtAcctTp__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to cdtrAgtAcctTp.
        /// </summary>
        public static string cdtrAgtAcctTp__Comment
        {
            get 
            {
                return ResourceManager.GetString("cdtrAgtAcctTp__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to КНП.
        /// </summary>
        public static string cdtrKnp__Title {
            get {
                return ResourceManager.GetString("cdtrKnp__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to КНП.
        /// </summary>
        public static string cdtrKnp__Comment
        {
            get 
            {
                return ResourceManager.GetString("cdtrKnp__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Номер документа.
        /// </summary>
        public static string cdtrNb__Title {
            get {
                return ResourceManager.GetString("cdtrNb__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Номер документа.
        /// </summary>
        public static string cdtrNb__Comment
        {
            get 
            {
                return ResourceManager.GetString("cdtrNb__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Дата документа.
        /// </summary>
        public static string cdtrRltdDt__Title {
            get {
                return ResourceManager.GetString("cdtrRltdDt__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Дата документа.
        /// </summary>
        public static string cdtrRltdDt__Comment
        {
            get 
            {
                return ResourceManager.GetString("cdtrRltdDt__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to instrPrty.
        /// </summary>
        public static string instrPrty__Title {
            get {
                return ResourceManager.GetString("instrPrty__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to instrPrty.
        /// </summary>
        public static string instrPrty__Comment
        {
            get 
            {
                return ResourceManager.GetString("instrPrty__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to instrLc.
        /// </summary>
        public static string instrLc__Title {
            get {
                return ResourceManager.GetString("instrLc__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to instrLc.
        /// </summary>
        public static string instrLc__Comment
        {
            get 
            {
                return ResourceManager.GetString("instrLc__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to orgBookAcc.
        /// </summary>
        public static string orgBookAcc__Title {
            get {
                return ResourceManager.GetString("orgBookAcc__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to orgBookAcc.
        /// </summary>
        public static string orgBookAcc__Comment
        {
            get 
            {
                return ResourceManager.GetString("orgBookAcc__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to body.
        /// </summary>
        public static string body__Title {
            get {
                return ResourceManager.GetString("body__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to body.
        /// </summary>
        public static string body__Comment
        {
            get 
            {
                return ResourceManager.GetString("body__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to isVolpay.
        /// </summary>
        public static string isVolpay__Title {
            get {
                return ResourceManager.GetString("isVolpay__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to isVolpay.
        /// </summary>
        public static string isVolpay__Comment
        {
            get 
            {
                return ResourceManager.GetString("isVolpay__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Да.
        /// </summary>
        public static string isVolpay__TrueText
        {
            get 
            {
                return ResourceManager.GetString("isVolpay__TrueText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Нет.
        /// </summary>
        public static string isVolpay__FalseText
        {
            get 
            {
                return ResourceManager.GetString("isVolpay__FalseText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to sts.
        /// </summary>
        public static string sts__Title {
            get {
                return ResourceManager.GetString("sts__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to sts.
        /// </summary>
        public static string sts__Comment
        {
            get 
            {
                return ResourceManager.GetString("sts__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to stsRelation.
        /// </summary>
        public static string stsRelation__Title {
            get {
                return ResourceManager.GetString("stsRelation__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to stsRelation.
        /// </summary>
        public static string stsRelation__Comment
        {
            get 
            {
                return ResourceManager.GetString("stsRelation__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to amntEq.
        /// </summary>
        public static string amntEq__Title {
            get {
                return ResourceManager.GetString("amntEq__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to amntEq.
        /// </summary>
        public static string amntEq__Comment
        {
            get 
            {
                return ResourceManager.GetString("amntEq__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to accCls.
        /// </summary>
        public static string accCls__Title {
            get {
                return ResourceManager.GetString("accCls__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to accCls.
        /// </summary>
        public static string accCls__Comment
        {
            get 
            {
                return ResourceManager.GetString("accCls__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to КБК.
        /// </summary>
        public static string bclass__Title {
            get {
                return ResourceManager.GetString("bclass__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to КБК.
        /// </summary>
        public static string bclass__Comment
        {
            get 
            {
                return ResourceManager.GetString("bclass__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to asgn.
        /// </summary>
        public static string asgn__Title {
            get {
                return ResourceManager.GetString("asgn__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to asgn.
        /// </summary>
        public static string asgn__Comment
        {
            get 
            {
                return ResourceManager.GetString("asgn__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Платеж.
        /// </summary>
        public static string isoPayment__VMTitle {
            get {
                return ResourceManager.GetString("isoPayment__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Платеж.
        /// </summary>
        public static string isoPayment__VMComment
        {
            get 
            {
                return ResourceManager.GetString("isoPayment__VMComment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Платеж.
        /// </summary>
        public static string isoPaymentMinimal__VMTitle {
            get {
                return ResourceManager.GetString("isoPaymentMinimal__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Платеж.
        /// </summary>
        public static string isoPaymentMinimal__VMComment
        {
            get 
            {
                return ResourceManager.GetString("isoPaymentMinimal__VMComment", resourceCulture);
            }
        }
    }
}