//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionaries.Areas.DIC.GeneratedResources {
    using global::System;
    using global::System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MT102_TBLResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal MT102_TBLResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dictionaries.Areas.DIC.GeneratedResources.MT102_TBLResources", typeof(MT102_TBLResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ102.
        /// </summary>
        public static string MT102_TBL__Title {
            get {
                return ResourceManager.GetString("MT102_TBL__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ102.
        /// </summary>
        public static string MT102_TBL__Comment
        {
            get 
            {
                return ResourceManager.GetString("MT102_TBL__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string MT102_TBL__DescriptionRtf
        {
            get 
            {
                return ResourceManager.GetString("MT102_TBL__DescriptionRtf", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Идентификатор.
        /// </summary>
        public static string id__Title {
            get {
                return ResourceManager.GetString("id__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Идентификатор.
        /// </summary>
        public static string id__Comment
        {
            get 
            {
                return ResourceManager.GetString("id__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Идентификатор документа.
        /// </summary>
        public static string ID_DOC__Title {
            get {
                return ResourceManager.GetString("ID_DOC__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Идентификатор документа.
        /// </summary>
        public static string ID_DOC__Comment
        {
            get 
            {
                return ResourceManager.GetString("ID_DOC__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to RELATIONREFERENSE.
        /// </summary>
        public static string RELATIONREFERENSE__Title {
            get {
                return ResourceManager.GetString("RELATIONREFERENSE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to RELATIONREFERENSE.
        /// </summary>
        public static string RELATIONREFERENSE__Comment
        {
            get 
            {
                return ResourceManager.GetString("RELATIONREFERENSE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to CURRENCYCODE.
        /// </summary>
        public static string CURRENCYCODE__Title {
            get {
                return ResourceManager.GetString("CURRENCYCODE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to CURRENCYCODE.
        /// </summary>
        public static string CURRENCYCODE__Comment
        {
            get 
            {
                return ResourceManager.GetString("CURRENCYCODE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to CURRENCYAMOUNT.
        /// </summary>
        public static string CURRENCYAMOUNT__Title {
            get {
                return ResourceManager.GetString("CURRENCYAMOUNT__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to CURRENCYAMOUNT.
        /// </summary>
        public static string CURRENCYAMOUNT__Comment
        {
            get 
            {
                return ResourceManager.GetString("CURRENCYAMOUNT__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to CURRENCYOPERATION.
        /// </summary>
        public static string CURRENCYOPERATION__Title {
            get {
                return ResourceManager.GetString("CURRENCYOPERATION__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to CURRENCYOPERATION.
        /// </summary>
        public static string CURRENCYOPERATION__Comment
        {
            get 
            {
                return ResourceManager.GetString("CURRENCYOPERATION__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERACCOUNT.
        /// </summary>
        public static string SENDERACCOUNT__Title {
            get {
                return ResourceManager.GetString("SENDERACCOUNT__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERACCOUNT.
        /// </summary>
        public static string SENDERACCOUNT__Comment
        {
            get 
            {
                return ResourceManager.GetString("SENDERACCOUNT__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERNAME.
        /// </summary>
        public static string SENDERNAME__Title {
            get {
                return ResourceManager.GetString("SENDERNAME__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERNAME.
        /// </summary>
        public static string SENDERNAME__Comment
        {
            get 
            {
                return ResourceManager.GetString("SENDERNAME__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERCHIEF.
        /// </summary>
        public static string SENDERCHIEF__Title {
            get {
                return ResourceManager.GetString("SENDERCHIEF__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERCHIEF.
        /// </summary>
        public static string SENDERCHIEF__Comment
        {
            get 
            {
                return ResourceManager.GetString("SENDERCHIEF__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERMAINBK.
        /// </summary>
        public static string SENDERMAINBK__Title {
            get {
                return ResourceManager.GetString("SENDERMAINBK__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERMAINBK.
        /// </summary>
        public static string SENDERMAINBK__Comment
        {
            get 
            {
                return ResourceManager.GetString("SENDERMAINBK__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERRNN.
        /// </summary>
        public static string SENDERRNN__Title {
            get {
                return ResourceManager.GetString("SENDERRNN__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERRNN.
        /// </summary>
        public static string SENDERRNN__Comment
        {
            get 
            {
                return ResourceManager.GetString("SENDERRNN__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERIRS.
        /// </summary>
        public static string SENDERIRS__Title {
            get {
                return ResourceManager.GetString("SENDERIRS__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERIRS.
        /// </summary>
        public static string SENDERIRS__Comment
        {
            get 
            {
                return ResourceManager.GetString("SENDERIRS__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERSECO.
        /// </summary>
        public static string SENDERSECO__Title {
            get {
                return ResourceManager.GetString("SENDERSECO__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERSECO.
        /// </summary>
        public static string SENDERSECO__Comment
        {
            get 
            {
                return ResourceManager.GetString("SENDERSECO__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERBNK.
        /// </summary>
        public static string SENDERBNK__Title {
            get {
                return ResourceManager.GetString("SENDERBNK__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to SENDERBNK.
        /// </summary>
        public static string SENDERBNK__Comment
        {
            get 
            {
                return ResourceManager.GetString("SENDERBNK__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BENEFBNK.
        /// </summary>
        public static string BENEFBNK__Title {
            get {
                return ResourceManager.GetString("BENEFBNK__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BENEFBNK.
        /// </summary>
        public static string BENEFBNK__Comment
        {
            get 
            {
                return ResourceManager.GetString("BENEFBNK__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BENEFACCOUNT.
        /// </summary>
        public static string BENEFACCOUNT__Title {
            get {
                return ResourceManager.GetString("BENEFACCOUNT__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BENEFACCOUNT.
        /// </summary>
        public static string BENEFACCOUNT__Comment
        {
            get 
            {
                return ResourceManager.GetString("BENEFACCOUNT__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BENEFNAME.
        /// </summary>
        public static string BENEFNAME__Title {
            get {
                return ResourceManager.GetString("BENEFNAME__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BENEFNAME.
        /// </summary>
        public static string BENEFNAME__Comment
        {
            get 
            {
                return ResourceManager.GetString("BENEFNAME__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BENEFRNN.
        /// </summary>
        public static string BENEFRNN__Title {
            get {
                return ResourceManager.GetString("BENEFRNN__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BENEFRNN.
        /// </summary>
        public static string BENEFRNN__Comment
        {
            get 
            {
                return ResourceManager.GetString("BENEFRNN__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BENEFIRS.
        /// </summary>
        public static string BENEFIRS__Title {
            get {
                return ResourceManager.GetString("BENEFIRS__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BENEFIRS.
        /// </summary>
        public static string BENEFIRS__Comment
        {
            get 
            {
                return ResourceManager.GetString("BENEFIRS__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BENEFSECO.
        /// </summary>
        public static string BENEFSECO__Title {
            get {
                return ResourceManager.GetString("BENEFSECO__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BENEFSECO.
        /// </summary>
        public static string BENEFSECO__Comment
        {
            get 
            {
                return ResourceManager.GetString("BENEFSECO__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_NUM.
        /// </summary>
        public static string DOC_NUM__Title {
            get {
                return ResourceManager.GetString("DOC_NUM__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_NUM.
        /// </summary>
        public static string DOC_NUM__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_NUM__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_DATE.
        /// </summary>
        public static string DOC_DATE__Title {
            get {
                return ResourceManager.GetString("DOC_DATE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_DATE.
        /// </summary>
        public static string DOC_DATE__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_DATE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_SEND.
        /// </summary>
        public static string DOC_SEND__Title {
            get {
                return ResourceManager.GetString("DOC_SEND__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_SEND.
        /// </summary>
        public static string DOC_SEND__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_SEND__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_VO.
        /// </summary>
        public static string DOC_VO__Title {
            get {
                return ResourceManager.GetString("DOC_VO__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_VO.
        /// </summary>
        public static string DOC_VO__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_VO__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PSO.
        /// </summary>
        public static string DOC_PSO__Title {
            get {
                return ResourceManager.GetString("DOC_PSO__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PSO.
        /// </summary>
        public static string DOC_PSO__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_PSO__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_KNP.
        /// </summary>
        public static string DOC_KNP__Title {
            get {
                return ResourceManager.GetString("DOC_KNP__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_KNP.
        /// </summary>
        public static string DOC_KNP__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_KNP__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BCLASS.
        /// </summary>
        public static string DOC_BCLASS__Title {
            get {
                return ResourceManager.GetString("DOC_BCLASS__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BCLASS.
        /// </summary>
        public static string DOC_BCLASS__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_BCLASS__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PRT.
        /// </summary>
        public static string DOC_PRT__Title {
            get {
                return ResourceManager.GetString("DOC_PRT__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PRT.
        /// </summary>
        public static string DOC_PRT__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_PRT__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_SIM.
        /// </summary>
        public static string DOC_SIM__Title {
            get {
                return ResourceManager.GetString("DOC_SIM__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_SIM.
        /// </summary>
        public static string DOC_SIM__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_SIM__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_ASSIGN.
        /// </summary>
        public static string DOC_ASSIGN__Title {
            get {
                return ResourceManager.GetString("DOC_ASSIGN__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_ASSIGN.
        /// </summary>
        public static string DOC_ASSIGN__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_ASSIGN__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_OPERATION.
        /// </summary>
        public static string DOC_OPERATION__Title {
            get {
                return ResourceManager.GetString("DOC_OPERATION__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_OPERATION.
        /// </summary>
        public static string DOC_OPERATION__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_OPERATION__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_SIC.
        /// </summary>
        public static string DOC_SIC__Title {
            get {
                return ResourceManager.GetString("DOC_SIC__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_SIC.
        /// </summary>
        public static string DOC_SIC__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_SIC__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_FM.
        /// </summary>
        public static string DOC_FM__Title {
            get {
                return ResourceManager.GetString("DOC_FM__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_FM.
        /// </summary>
        public static string DOC_FM__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_FM__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_NM.
        /// </summary>
        public static string DOC_NM__Title {
            get {
                return ResourceManager.GetString("DOC_NM__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_NM.
        /// </summary>
        public static string DOC_NM__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_NM__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_FT.
        /// </summary>
        public static string DOC_FT__Title {
            get {
                return ResourceManager.GetString("DOC_FT__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_FT.
        /// </summary>
        public static string DOC_FT__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_FT__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_DT.
        /// </summary>
        public static string DOC_DT__Title {
            get {
                return ResourceManager.GetString("DOC_DT__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_DT.
        /// </summary>
        public static string DOC_DT__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_DT__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_LA.
        /// </summary>
        public static string DOC_LA__Title {
            get {
                return ResourceManager.GetString("DOC_LA__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_LA.
        /// </summary>
        public static string DOC_LA__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_LA__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_RNN.
        /// </summary>
        public static string DOC_RNN__Title {
            get {
                return ResourceManager.GetString("DOC_RNN__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_RNN.
        /// </summary>
        public static string DOC_RNN__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_RNN__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to seqlfvalue.
        /// </summary>
        public static string seqlfvalue__Title {
            get {
                return ResourceManager.GetString("seqlfvalue__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to seqlfvalue.
        /// </summary>
        public static string seqlfvalue__Comment
        {
            get 
            {
                return ResourceManager.GetString("seqlfvalue__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossCurrencyCode.
        /// </summary>
        public static string crossCurrencyCode__Title {
            get {
                return ResourceManager.GetString("crossCurrencyCode__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossCurrencyCode.
        /// </summary>
        public static string crossCurrencyCode__Comment
        {
            get 
            {
                return ResourceManager.GetString("crossCurrencyCode__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossCurrencyAmount.
        /// </summary>
        public static string crossCurrencyAmount__Title {
            get {
                return ResourceManager.GetString("crossCurrencyAmount__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossCurrencyAmount.
        /// </summary>
        public static string crossCurrencyAmount__Comment
        {
            get 
            {
                return ResourceManager.GetString("crossCurrencyAmount__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossExchange.
        /// </summary>
        public static string crossExchange__Title {
            get {
                return ResourceManager.GetString("crossExchange__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossExchange.
        /// </summary>
        public static string crossExchange__Comment
        {
            get 
            {
                return ResourceManager.GetString("crossExchange__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossSenderCountry.
        /// </summary>
        public static string crossSenderCountry__Title {
            get {
                return ResourceManager.GetString("crossSenderCountry__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossSenderCountry.
        /// </summary>
        public static string crossSenderCountry__Comment
        {
            get 
            {
                return ResourceManager.GetString("crossSenderCountry__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossPayeeCountry.
        /// </summary>
        public static string crossPayeeCountry__Title {
            get {
                return ResourceManager.GetString("crossPayeeCountry__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossPayeeCountry.
        /// </summary>
        public static string crossPayeeCountry__Comment
        {
            get 
            {
                return ResourceManager.GetString("crossPayeeCountry__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossChargeCost.
        /// </summary>
        public static string crossChargeCost__Title {
            get {
                return ResourceManager.GetString("crossChargeCost__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossChargeCost.
        /// </summary>
        public static string crossChargeCost__Comment
        {
            get 
            {
                return ResourceManager.GetString("crossChargeCost__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ102.
        /// </summary>
        public static string MT102_TBL__VMTitle {
            get {
                return ResourceManager.GetString("MT102_TBL__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ102.
        /// </summary>
        public static string MT102_TBL__VMComment
        {
            get 
            {
                return ResourceManager.GetString("MT102_TBL__VMComment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ102.
        /// </summary>
        public static string MT102_TBLMinimal__VMTitle {
            get {
                return ResourceManager.GetString("MT102_TBLMinimal__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ102.
        /// </summary>
        public static string MT102_TBLMinimal__VMComment
        {
            get 
            {
                return ResourceManager.GetString("MT102_TBLMinimal__VMComment", resourceCulture);
            }
        }
    }
}