//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionaries.Areas.DIC.GeneratedResources {
    using global::System;
    using global::System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MT100_TBLResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal MT100_TBLResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dictionaries.Areas.DIC.GeneratedResources.MT100_TBLResources", typeof(MT100_TBLResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ100.
        /// </summary>
        public static string MT100_TBL__Title {
            get {
                return ResourceManager.GetString("MT100_TBL__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ100.
        /// </summary>
        public static string MT100_TBL__Comment
        {
            get 
            {
                return ResourceManager.GetString("MT100_TBL__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string MT100_TBL__DescriptionRtf
        {
            get 
            {
                return ResourceManager.GetString("MT100_TBL__DescriptionRtf", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Иденитфикатор документа.
        /// </summary>
        public static string id__Title {
            get {
                return ResourceManager.GetString("id__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Иденитфикатор документа.
        /// </summary>
        public static string id__Comment
        {
            get 
            {
                return ResourceManager.GetString("id__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Идентификатор собщение.
        /// </summary>
        public static string ID_MESSAGE__Title {
            get {
                return ResourceManager.GetString("ID_MESSAGE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Идентификатор собщение.
        /// </summary>
        public static string ID_MESSAGE__Comment
        {
            get 
            {
                return ResourceManager.GetString("ID_MESSAGE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Ссылка на документ.
        /// </summary>
        public static string DOC_REFERENCE__Title {
            get {
                return ResourceManager.GetString("DOC_REFERENCE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Ссылка на документ.
        /// </summary>
        public static string DOC_REFERENCE__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_REFERENCE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PAYADD.
        /// </summary>
        public static string DOC_PAYADD__Title {
            get {
                return ResourceManager.GetString("DOC_PAYADD__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PAYADD.
        /// </summary>
        public static string DOC_PAYADD__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_PAYADD__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PAYCODE.
        /// </summary>
        public static string DOC_PAYCODE__Title {
            get {
                return ResourceManager.GetString("DOC_PAYCODE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PAYCODE.
        /// </summary>
        public static string DOC_PAYCODE__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_PAYCODE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Операция документа.
        /// </summary>
        public static string DOC_OPERATION__Title {
            get {
                return ResourceManager.GetString("DOC_OPERATION__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Операция документа.
        /// </summary>
        public static string DOC_OPERATION__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_OPERATION__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORACCOUNT.
        /// </summary>
        public static string DOC_INITIATORACCOUNT__Title {
            get {
                return ResourceManager.GetString("DOC_INITIATORACCOUNT__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORACCOUNT.
        /// </summary>
        public static string DOC_INITIATORACCOUNT__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_INITIATORACCOUNT__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORRNN.
        /// </summary>
        public static string DOC_INITIATORRNN__Title {
            get {
                return ResourceManager.GetString("DOC_INITIATORRNN__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORRNN.
        /// </summary>
        public static string DOC_INITIATORRNN__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_INITIATORRNN__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORCHIEF.
        /// </summary>
        public static string DOC_INITIATORCHIEF__Title {
            get {
                return ResourceManager.GetString("DOC_INITIATORCHIEF__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORCHIEF.
        /// </summary>
        public static string DOC_INITIATORCHIEF__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_INITIATORCHIEF__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORMAINBK.
        /// </summary>
        public static string DOC_INITIATORMAINBK__Title {
            get {
                return ResourceManager.GetString("DOC_INITIATORMAINBK__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORMAINBK.
        /// </summary>
        public static string DOC_INITIATORMAINBK__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_INITIATORMAINBK__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORNAME.
        /// </summary>
        public static string DOC_INITIATORNAME__Title {
            get {
                return ResourceManager.GetString("DOC_INITIATORNAME__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORNAME.
        /// </summary>
        public static string DOC_INITIATORNAME__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_INITIATORNAME__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORIRS.
        /// </summary>
        public static string DOC_INITIATORIRS__Title {
            get {
                return ResourceManager.GetString("DOC_INITIATORIRS__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORIRS.
        /// </summary>
        public static string DOC_INITIATORIRS__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_INITIATORIRS__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORSECO.
        /// </summary>
        public static string DOC_INITIATORSECO__Title {
            get {
                return ResourceManager.GetString("DOC_INITIATORSECO__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORSECO.
        /// </summary>
        public static string DOC_INITIATORSECO__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_INITIATORSECO__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORBNK.
        /// </summary>
        public static string DOC_INITIATORBNK__Title {
            get {
                return ResourceManager.GetString("DOC_INITIATORBNK__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORBNK.
        /// </summary>
        public static string DOC_INITIATORBNK__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_INITIATORBNK__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORCORRBBNK.
        /// </summary>
        public static string DOC_INITIATORCORRBBNK__Title {
            get {
                return ResourceManager.GetString("DOC_INITIATORCORRBBNK__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORCORRBBNK.
        /// </summary>
        public static string DOC_INITIATORCORRBBNK__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_INITIATORCORRBBNK__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORCORRACCOUNT.
        /// </summary>
        public static string DOC_INITIATORCORRACCOUNT__Title {
            get {
                return ResourceManager.GetString("DOC_INITIATORCORRACCOUNT__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORCORRACCOUNT.
        /// </summary>
        public static string DOC_INITIATORCORRACCOUNT__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_INITIATORCORRACCOUNT__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFCORRRBNK.
        /// </summary>
        public static string DOC_BENEFCORRRBNK__Title {
            get {
                return ResourceManager.GetString("DOC_BENEFCORRRBNK__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFCORRRBNK.
        /// </summary>
        public static string DOC_BENEFCORRRBNK__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_BENEFCORRRBNK__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFCORRACCOUNT.
        /// </summary>
        public static string DOC_BENEFCORRACCOUNT__Title {
            get {
                return ResourceManager.GetString("DOC_BENEFCORRACCOUNT__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFCORRACCOUNT.
        /// </summary>
        public static string DOC_BENEFCORRACCOUNT__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_BENEFCORRACCOUNT__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFBNK.
        /// </summary>
        public static string DOC_BENEFBNK__Title {
            get {
                return ResourceManager.GetString("DOC_BENEFBNK__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFBNK.
        /// </summary>
        public static string DOC_BENEFBNK__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_BENEFBNK__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFACCOUNT.
        /// </summary>
        public static string DOC_BENEFACCOUNT__Title {
            get {
                return ResourceManager.GetString("DOC_BENEFACCOUNT__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFACCOUNT.
        /// </summary>
        public static string DOC_BENEFACCOUNT__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_BENEFACCOUNT__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFRNN.
        /// </summary>
        public static string DOC_BENEFRNN__Title {
            get {
                return ResourceManager.GetString("DOC_BENEFRNN__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFRNN.
        /// </summary>
        public static string DOC_BENEFRNN__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_BENEFRNN__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFNAME.
        /// </summary>
        public static string DOC_BENEFNAME__Title {
            get {
                return ResourceManager.GetString("DOC_BENEFNAME__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFNAME.
        /// </summary>
        public static string DOC_BENEFNAME__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_BENEFNAME__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFIRS.
        /// </summary>
        public static string DOC_BENEFIRS__Title {
            get {
                return ResourceManager.GetString("DOC_BENEFIRS__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFIRS.
        /// </summary>
        public static string DOC_BENEFIRS__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_BENEFIRS__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFSECO.
        /// </summary>
        public static string DOC_BENEFSECO__Title {
            get {
                return ResourceManager.GetString("DOC_BENEFSECO__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFSECO.
        /// </summary>
        public static string DOC_BENEFSECO__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_BENEFSECO__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Номер документа.
        /// </summary>
        public static string DOC_NUM__Title {
            get {
                return ResourceManager.GetString("DOC_NUM__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Номер документа.
        /// </summary>
        public static string DOC_NUM__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_NUM__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Дата документа.
        /// </summary>
        public static string DOC_DATE__Title {
            get {
                return ResourceManager.GetString("DOC_DATE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Дата документа.
        /// </summary>
        public static string DOC_DATE__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_DATE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Отправить документ.
        /// </summary>
        public static string DOC_SEND__Title {
            get {
                return ResourceManager.GetString("DOC_SEND__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Отправить документ.
        /// </summary>
        public static string DOC_SEND__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_SEND__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_VO.
        /// </summary>
        public static string DOC_VO__Title {
            get {
                return ResourceManager.GetString("DOC_VO__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_VO.
        /// </summary>
        public static string DOC_VO__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_VO__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PSO.
        /// </summary>
        public static string DOC_PSO__Title {
            get {
                return ResourceManager.GetString("DOC_PSO__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PSO.
        /// </summary>
        public static string DOC_PSO__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_PSO__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_KNP.
        /// </summary>
        public static string DOC_KNP__Title {
            get {
                return ResourceManager.GetString("DOC_KNP__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_KNP.
        /// </summary>
        public static string DOC_KNP__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_KNP__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BCLASS.
        /// </summary>
        public static string DOC_BCLASS__Title {
            get {
                return ResourceManager.GetString("DOC_BCLASS__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BCLASS.
        /// </summary>
        public static string DOC_BCLASS__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_BCLASS__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PRT.
        /// </summary>
        public static string DOC_PRT__Title {
            get {
                return ResourceManager.GetString("DOC_PRT__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PRT.
        /// </summary>
        public static string DOC_PRT__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_PRT__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_SIM.
        /// </summary>
        public static string DOC_SIM__Title {
            get {
                return ResourceManager.GetString("DOC_SIM__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_SIM.
        /// </summary>
        public static string DOC_SIM__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_SIM__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_ASSIGN.
        /// </summary>
        public static string DOC_ASSIGN__Title {
            get {
                return ResourceManager.GetString("DOC_ASSIGN__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_ASSIGN.
        /// </summary>
        public static string DOC_ASSIGN__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_ASSIGN__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Добавить документ.
        /// </summary>
        public static string DOC_ADD__Title {
            get {
                return ResourceManager.GetString("DOC_ADD__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Добавить документ.
        /// </summary>
        public static string DOC_ADD__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_ADD__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PAYAMOUNT.
        /// </summary>
        public static string DOC_PAYAMOUNT__Title {
            get {
                return ResourceManager.GetString("DOC_PAYAMOUNT__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PAYAMOUNT.
        /// </summary>
        public static string DOC_PAYAMOUNT__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_PAYAMOUNT__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_RELATIONREFERENSE.
        /// </summary>
        public static string DOC_RELATIONREFERENSE__Title {
            get {
                return ResourceManager.GetString("DOC_RELATIONREFERENSE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_RELATIONREFERENSE.
        /// </summary>
        public static string DOC_RELATIONREFERENSE__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_RELATIONREFERENSE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PRINTED.
        /// </summary>
        public static string DOC_PRINTED__Title {
            get {
                return ResourceManager.GetString("DOC_PRINTED__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_PRINTED.
        /// </summary>
        public static string DOC_PRINTED__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_PRINTED__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to lfvalue.
        /// </summary>
        public static string lfvalue__Title {
            get {
                return ResourceManager.GetString("lfvalue__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to lfvalue.
        /// </summary>
        public static string lfvalue__Comment
        {
            get 
            {
                return ResourceManager.GetString("lfvalue__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to PSTATE.
        /// </summary>
        public static string PSTATE__Title {
            get {
                return ResourceManager.GetString("PSTATE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to PSTATE.
        /// </summary>
        public static string PSTATE__Comment
        {
            get 
            {
                return ResourceManager.GetString("PSTATE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Да.
        /// </summary>
        public static string PSTATE__TrueText
        {
            get 
            {
                return ResourceManager.GetString("PSTATE__TrueText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Нет.
        /// </summary>
        public static string PSTATE__FalseText
        {
            get 
            {
                return ResourceManager.GetString("PSTATE__FalseText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORIDN.
        /// </summary>
        public static string DOC_INITIATORIDN__Title {
            get {
                return ResourceManager.GetString("DOC_INITIATORIDN__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_INITIATORIDN.
        /// </summary>
        public static string DOC_INITIATORIDN__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_INITIATORIDN__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFIDN.
        /// </summary>
        public static string DOC_BENEFIDN__Title {
            get {
                return ResourceManager.GetString("DOC_BENEFIDN__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DOC_BENEFIDN.
        /// </summary>
        public static string DOC_BENEFIDN__Comment
        {
            get 
            {
                return ResourceManager.GetString("DOC_BENEFIDN__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to COMMON_DOC_TYPE.
        /// </summary>
        public static string COMMON_DOC_TYPE__Title {
            get {
                return ResourceManager.GetString("COMMON_DOC_TYPE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to COMMON_DOC_TYPE.
        /// </summary>
        public static string COMMON_DOC_TYPE__Comment
        {
            get 
            {
                return ResourceManager.GetString("COMMON_DOC_TYPE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to isENTERPRISEWAGE.
        /// </summary>
        public static string isENTERPRISEWAGE__Title {
            get {
                return ResourceManager.GetString("isENTERPRISEWAGE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to isENTERPRISEWAGE.
        /// </summary>
        public static string isENTERPRISEWAGE__Comment
        {
            get 
            {
                return ResourceManager.GetString("isENTERPRISEWAGE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to paymentType.
        /// </summary>
        public static string paymentType__Title {
            get {
                return ResourceManager.GetString("paymentType__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to paymentType.
        /// </summary>
        public static string paymentType__Comment
        {
            get 
            {
                return ResourceManager.GetString("paymentType__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossCurrencyCode.
        /// </summary>
        public static string crossCurrencyCode__Title {
            get {
                return ResourceManager.GetString("crossCurrencyCode__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossCurrencyCode.
        /// </summary>
        public static string crossCurrencyCode__Comment
        {
            get 
            {
                return ResourceManager.GetString("crossCurrencyCode__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossCurrencyAmount.
        /// </summary>
        public static string crossCurrencyAmount__Title {
            get {
                return ResourceManager.GetString("crossCurrencyAmount__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossCurrencyAmount.
        /// </summary>
        public static string crossCurrencyAmount__Comment
        {
            get 
            {
                return ResourceManager.GetString("crossCurrencyAmount__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossExchange.
        /// </summary>
        public static string crossExchange__Title {
            get {
                return ResourceManager.GetString("crossExchange__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossExchange.
        /// </summary>
        public static string crossExchange__Comment
        {
            get 
            {
                return ResourceManager.GetString("crossExchange__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossSenderCountry.
        /// </summary>
        public static string crossSenderCountry__Title {
            get {
                return ResourceManager.GetString("crossSenderCountry__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossSenderCountry.
        /// </summary>
        public static string crossSenderCountry__Comment
        {
            get 
            {
                return ResourceManager.GetString("crossSenderCountry__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossPayeeCountry.
        /// </summary>
        public static string crossPayeeCountry__Title {
            get {
                return ResourceManager.GetString("crossPayeeCountry__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossPayeeCountry.
        /// </summary>
        public static string crossPayeeCountry__Comment
        {
            get 
            {
                return ResourceManager.GetString("crossPayeeCountry__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossChargeCost.
        /// </summary>
        public static string crossChargeCost__Title {
            get {
                return ResourceManager.GetString("crossChargeCost__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to crossChargeCost.
        /// </summary>
        public static string crossChargeCost__Comment
        {
            get 
            {
                return ResourceManager.GetString("crossChargeCost__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to doc_type.
        /// </summary>
        public static string doc_type__Title {
            get {
                return ResourceManager.GetString("doc_type__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to doc_type.
        /// </summary>
        public static string doc_type__Comment
        {
            get 
            {
                return ResourceManager.GetString("doc_type__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to operDate.
        /// </summary>
        public static string operDate__Title {
            get {
                return ResourceManager.GetString("operDate__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to operDate.
        /// </summary>
        public static string operDate__Comment
        {
            get 
            {
                return ResourceManager.GetString("operDate__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to psstView.
        /// </summary>
        public static string psstView__Title {
            get {
                return ResourceManager.GetString("psstView__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to psstView.
        /// </summary>
        public static string psstView__Comment
        {
            get 
            {
                return ResourceManager.GetString("psstView__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to senderPhone.
        /// </summary>
        public static string senderPhone__Title {
            get {
                return ResourceManager.GetString("senderPhone__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to senderPhone.
        /// </summary>
        public static string senderPhone__Comment
        {
            get 
            {
                return ResourceManager.GetString("senderPhone__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to addresseePhone.
        /// </summary>
        public static string addresseePhone__Title {
            get {
                return ResourceManager.GetString("addresseePhone__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to addresseePhone.
        /// </summary>
        public static string addresseePhone__Comment
        {
            get 
            {
                return ResourceManager.GetString("addresseePhone__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to payPriority.
        /// </summary>
        public static string payPriority__Title {
            get {
                return ResourceManager.GetString("payPriority__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to payPriority.
        /// </summary>
        public static string payPriority__Comment
        {
            get 
            {
                return ResourceManager.GetString("payPriority__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Да.
        /// </summary>
        public static string payPriority__TrueText
        {
            get 
            {
                return ResourceManager.GetString("payPriority__TrueText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Нет.
        /// </summary>
        public static string payPriority__FalseText
        {
            get 
            {
                return ResourceManager.GetString("payPriority__FalseText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to isUseLimit.
        /// </summary>
        public static string isUseLimit__Title {
            get {
                return ResourceManager.GetString("isUseLimit__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to isUseLimit.
        /// </summary>
        public static string isUseLimit__Comment
        {
            get 
            {
                return ResourceManager.GetString("isUseLimit__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Да.
        /// </summary>
        public static string isUseLimit__TrueText
        {
            get 
            {
                return ResourceManager.GetString("isUseLimit__TrueText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Нет.
        /// </summary>
        public static string isUseLimit__FalseText
        {
            get 
            {
                return ResourceManager.GetString("isUseLimit__FalseText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to REFlimitId.
        /// </summary>
        public static string REFlimitId__Title {
            get {
                return ResourceManager.GetString("REFlimitId__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to REFlimitId.
        /// </summary>
        public static string REFlimitId__Comment
        {
            get 
            {
                return ResourceManager.GetString("REFlimitId__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ100.
        /// </summary>
        public static string MT100_TBL__VMTitle {
            get {
                return ResourceManager.GetString("MT100_TBL__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ100.
        /// </summary>
        public static string MT100_TBL__VMComment
        {
            get 
            {
                return ResourceManager.GetString("MT100_TBL__VMComment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ100.
        /// </summary>
        public static string MT100_TBLMinimal__VMTitle {
            get {
                return ResourceManager.GetString("MT100_TBLMinimal__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ100.
        /// </summary>
        public static string MT100_TBLMinimal__VMComment
        {
            get 
            {
                return ResourceManager.GetString("MT100_TBLMinimal__VMComment", resourceCulture);
            }
        }
    }
}