//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionaries.Areas.DIC.GeneratedResources {
    using global::System;
    using global::System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MT950_TBLResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal MT950_TBLResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dictionaries.Areas.DIC.GeneratedResources.MT950_TBLResources", typeof(MT950_TBLResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ950.
        /// </summary>
        public static string MT950_TBL__Title {
            get {
                return ResourceManager.GetString("MT950_TBL__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ950.
        /// </summary>
        public static string MT950_TBL__Comment
        {
            get 
            {
                return ResourceManager.GetString("MT950_TBL__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string MT950_TBL__DescriptionRtf
        {
            get 
            {
                return ResourceManager.GetString("MT950_TBL__DescriptionRtf", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to ID_EXTRACT.
        /// </summary>
        public static string id__Title {
            get {
                return ResourceManager.GetString("id__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to ID_EXTRACT.
        /// </summary>
        public static string id__Comment
        {
            get 
            {
                return ResourceManager.GetString("id__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to REFERENSE.
        /// </summary>
        public static string REFERENSE__Title {
            get {
                return ResourceManager.GetString("REFERENSE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to REFERENSE.
        /// </summary>
        public static string REFERENSE__Comment
        {
            get 
            {
                return ResourceManager.GetString("REFERENSE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BIC.
        /// </summary>
        public static string BIC__Title {
            get {
                return ResourceManager.GetString("BIC__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to BIC.
        /// </summary>
        public static string BIC__Comment
        {
            get 
            {
                return ResourceManager.GetString("BIC__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to ACCOUNT.
        /// </summary>
        public static string ACCOUNT__Title {
            get {
                return ResourceManager.GetString("ACCOUNT__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to ACCOUNT.
        /// </summary>
        public static string ACCOUNT__Comment
        {
            get 
            {
                return ResourceManager.GetString("ACCOUNT__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to FNUM.
        /// </summary>
        public static string FNUM__Title {
            get {
                return ResourceManager.GetString("FNUM__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to FNUM.
        /// </summary>
        public static string FNUM__Comment
        {
            get 
            {
                return ResourceManager.GetString("FNUM__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to FCOUNT.
        /// </summary>
        public static string FCOUNT__Title {
            get {
                return ResourceManager.GetString("FCOUNT__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to FCOUNT.
        /// </summary>
        public static string FCOUNT__Comment
        {
            get 
            {
                return ResourceManager.GetString("FCOUNT__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to FSTART.
        /// </summary>
        public static string FSTART__Title {
            get {
                return ResourceManager.GetString("FSTART__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to FSTART.
        /// </summary>
        public static string FSTART__Comment
        {
            get 
            {
                return ResourceManager.GetString("FSTART__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to OPER_A.
        /// </summary>
        public static string OPER_A__Title {
            get {
                return ResourceManager.GetString("OPER_A__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to OPER_A.
        /// </summary>
        public static string OPER_A__Comment
        {
            get 
            {
                return ResourceManager.GetString("OPER_A__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DATE_A.
        /// </summary>
        public static string DATE_A__Title {
            get {
                return ResourceManager.GetString("DATE_A__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DATE_A.
        /// </summary>
        public static string DATE_A__Comment
        {
            get 
            {
                return ResourceManager.GetString("DATE_A__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to CODE_A.
        /// </summary>
        public static string CODE_A__Title {
            get {
                return ResourceManager.GetString("CODE_A__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to CODE_A.
        /// </summary>
        public static string CODE_A__Comment
        {
            get 
            {
                return ResourceManager.GetString("CODE_A__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to AMOUNT_A.
        /// </summary>
        public static string AMOUNT_A__Title {
            get {
                return ResourceManager.GetString("AMOUNT_A__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to AMOUNT_A.
        /// </summary>
        public static string AMOUNT_A__Comment
        {
            get 
            {
                return ResourceManager.GetString("AMOUNT_A__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to FEND.
        /// </summary>
        public static string FEND__Title {
            get {
                return ResourceManager.GetString("FEND__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to FEND.
        /// </summary>
        public static string FEND__Comment
        {
            get 
            {
                return ResourceManager.GetString("FEND__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to OPER_C.
        /// </summary>
        public static string OPER_C__Title {
            get {
                return ResourceManager.GetString("OPER_C__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to OPER_C.
        /// </summary>
        public static string OPER_C__Comment
        {
            get 
            {
                return ResourceManager.GetString("OPER_C__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DATE_C.
        /// </summary>
        public static string DATE_C__Title {
            get {
                return ResourceManager.GetString("DATE_C__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to DATE_C.
        /// </summary>
        public static string DATE_C__Comment
        {
            get 
            {
                return ResourceManager.GetString("DATE_C__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to CODE_C.
        /// </summary>
        public static string CODE_C__Title {
            get {
                return ResourceManager.GetString("CODE_C__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to CODE_C.
        /// </summary>
        public static string CODE_C__Comment
        {
            get 
            {
                return ResourceManager.GetString("CODE_C__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to AMOUNT_C.
        /// </summary>
        public static string AMOUNT_C__Title {
            get {
                return ResourceManager.GetString("AMOUNT_C__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to AMOUNT_C.
        /// </summary>
        public static string AMOUNT_C__Comment
        {
            get 
            {
                return ResourceManager.GetString("AMOUNT_C__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to FCODENAME.
        /// </summary>
        public static string FCODENAME__Title {
            get {
                return ResourceManager.GetString("FCODENAME__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to FCODENAME.
        /// </summary>
        public static string FCODENAME__Comment
        {
            get 
            {
                return ResourceManager.GetString("FCODENAME__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to ID_MESSAGE.
        /// </summary>
        public static string ID_MESSAGE__Title {
            get {
                return ResourceManager.GetString("ID_MESSAGE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to ID_MESSAGE.
        /// </summary>
        public static string ID_MESSAGE__Comment
        {
            get 
            {
                return ResourceManager.GetString("ID_MESSAGE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to FTYPE.
        /// </summary>
        public static string FTYPE__Title {
            get {
                return ResourceManager.GetString("FTYPE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to FTYPE.
        /// </summary>
        public static string FTYPE__Comment
        {
            get 
            {
                return ResourceManager.GetString("FTYPE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to FSYSTEM.
        /// </summary>
        public static string FSYSTEM__Title {
            get {
                return ResourceManager.GetString("FSYSTEM__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to FSYSTEM.
        /// </summary>
        public static string FSYSTEM__Comment
        {
            get 
            {
                return ResourceManager.GetString("FSYSTEM__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ950.
        /// </summary>
        public static string MT950_TBL__VMTitle {
            get {
                return ResourceManager.GetString("MT950_TBL__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ950.
        /// </summary>
        public static string MT950_TBL__VMComment
        {
            get 
            {
                return ResourceManager.GetString("MT950_TBL__VMComment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ950.
        /// </summary>
        public static string MT950_TBLMinimal__VMTitle {
            get {
                return ResourceManager.GetString("MT950_TBLMinimal__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение - МТ950.
        /// </summary>
        public static string MT950_TBLMinimal__VMComment
        {
            get 
            {
                return ResourceManager.GetString("MT950_TBLMinimal__VMComment", resourceCulture);
            }
        }
    }
}