//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionaries.Areas.DIC.GeneratedResources {
    using global::System;
    using global::System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MT_Messages_TBLResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal MT_Messages_TBLResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dictionaries.Areas.DIC.GeneratedResources.MT_Messages_TBLResources", typeof(MT_Messages_TBLResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Сообщение TBL.
        /// </summary>
        public static string MT_Messages_TBL__Title {
            get {
                return ResourceManager.GetString("MT_Messages_TBL__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение TBL.
        /// </summary>
        public static string MT_Messages_TBL__Comment
        {
            get 
            {
                return ResourceManager.GetString("MT_Messages_TBL__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string MT_Messages_TBL__DescriptionRtf
        {
            get 
            {
                return ResourceManager.GetString("MT_Messages_TBL__DescriptionRtf", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to ID_MESSAGE.
        /// </summary>
        public static string id__Title {
            get {
                return ResourceManager.GetString("id__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to ID_MESSAGE.
        /// </summary>
        public static string id__Comment
        {
            get 
            {
                return ResourceManager.GetString("id__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_BODY.
        /// </summary>
        public static string MESSAGE_BODY__Title {
            get {
                return ResourceManager.GetString("MESSAGE_BODY__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_BODY.
        /// </summary>
        public static string MESSAGE_BODY__Comment
        {
            get 
            {
                return ResourceManager.GetString("MESSAGE_BODY__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_DATE.
        /// </summary>
        public static string MESSAGE_DATE__Title {
            get {
                return ResourceManager.GetString("MESSAGE_DATE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_DATE.
        /// </summary>
        public static string MESSAGE_DATE__Comment
        {
            get 
            {
                return ResourceManager.GetString("MESSAGE_DATE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_SESSION.
        /// </summary>
        public static string MESSAGE_SESSION__Title {
            get {
                return ResourceManager.GetString("MESSAGE_SESSION__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_SESSION.
        /// </summary>
        public static string MESSAGE_SESSION__Comment
        {
            get 
            {
                return ResourceManager.GetString("MESSAGE_SESSION__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_REFERENS.
        /// </summary>
        public static string MESSAGE_REFERENS__Title {
            get {
                return ResourceManager.GetString("MESSAGE_REFERENS__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_REFERENS.
        /// </summary>
        public static string MESSAGE_REFERENS__Comment
        {
            get 
            {
                return ResourceManager.GetString("MESSAGE_REFERENS__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_NAMESUB.
        /// </summary>
        public static string MESSAGE_NAMESUB__Title {
            get {
                return ResourceManager.GetString("MESSAGE_NAMESUB__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_NAMESUB.
        /// </summary>
        public static string MESSAGE_NAMESUB__Comment
        {
            get 
            {
                return ResourceManager.GetString("MESSAGE_NAMESUB__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_FLAGIO.
        /// </summary>
        public static string MESSAGE_FLAGIO__Title {
            get {
                return ResourceManager.GetString("MESSAGE_FLAGIO__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_FLAGIO.
        /// </summary>
        public static string MESSAGE_FLAGIO__Comment
        {
            get 
            {
                return ResourceManager.GetString("MESSAGE_FLAGIO__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_STATE.
        /// </summary>
        public static string MESSAGE_STATE__Title {
            get {
                return ResourceManager.GetString("MESSAGE_STATE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_STATE.
        /// </summary>
        public static string MESSAGE_STATE__Comment
        {
            get 
            {
                return ResourceManager.GetString("MESSAGE_STATE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_TYPE.
        /// </summary>
        public static string MESSAGE_TYPE__Title {
            get {
                return ResourceManager.GetString("MESSAGE_TYPE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_TYPE.
        /// </summary>
        public static string MESSAGE_TYPE__Comment
        {
            get 
            {
                return ResourceManager.GetString("MESSAGE_TYPE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_TIMEIN.
        /// </summary>
        public static string MESSAGE_TIMEIN__Title {
            get {
                return ResourceManager.GetString("MESSAGE_TIMEIN__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_TIMEIN.
        /// </summary>
        public static string MESSAGE_TIMEIN__Comment
        {
            get 
            {
                return ResourceManager.GetString("MESSAGE_TIMEIN__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_TIMEOUT.
        /// </summary>
        public static string MESSAGE_TIMEOUT__Title {
            get {
                return ResourceManager.GetString("MESSAGE_TIMEOUT__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_TIMEOUT.
        /// </summary>
        public static string MESSAGE_TIMEOUT__Comment
        {
            get 
            {
                return ResourceManager.GetString("MESSAGE_TIMEOUT__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_INTERNAL_REFERENSE.
        /// </summary>
        public static string MESSAGE_INTERNAL_REFERENSE__Title {
            get {
                return ResourceManager.GetString("MESSAGE_INTERNAL_REFERENSE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_INTERNAL_REFERENSE.
        /// </summary>
        public static string MESSAGE_INTERNAL_REFERENSE__Comment
        {
            get 
            {
                return ResourceManager.GetString("MESSAGE_INTERNAL_REFERENSE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_ERROR.
        /// </summary>
        public static string MESSAGE_ERROR__Title {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_ERROR.
        /// </summary>
        public static string MESSAGE_ERROR__Comment
        {
            get 
            {
                return ResourceManager.GetString("MESSAGE_ERROR__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_OWNER.
        /// </summary>
        public static string MESSAGE_OWNER__Title {
            get {
                return ResourceManager.GetString("MESSAGE_OWNER__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_OWNER.
        /// </summary>
        public static string MESSAGE_OWNER__Comment
        {
            get 
            {
                return ResourceManager.GetString("MESSAGE_OWNER__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_PACKET.
        /// </summary>
        public static string MESSAGE_PACKET__Title {
            get {
                return ResourceManager.GetString("MESSAGE_PACKET__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to MESSAGE_PACKET.
        /// </summary>
        public static string MESSAGE_PACKET__Comment
        {
            get 
            {
                return ResourceManager.GetString("MESSAGE_PACKET__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to M_DOC_USER.
        /// </summary>
        public static string M_DOC_USER__Title {
            get {
                return ResourceManager.GetString("M_DOC_USER__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to M_DOC_USER.
        /// </summary>
        public static string M_DOC_USER__Comment
        {
            get 
            {
                return ResourceManager.GetString("M_DOC_USER__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to M_DOC_NUM.
        /// </summary>
        public static string M_DOC_NUM__Title {
            get {
                return ResourceManager.GetString("M_DOC_NUM__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to M_DOC_NUM.
        /// </summary>
        public static string M_DOC_NUM__Comment
        {
            get 
            {
                return ResourceManager.GetString("M_DOC_NUM__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to M_DOC_DATE.
        /// </summary>
        public static string M_DOC_DATE__Title {
            get {
                return ResourceManager.GetString("M_DOC_DATE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to M_DOC_DATE.
        /// </summary>
        public static string M_DOC_DATE__Comment
        {
            get 
            {
                return ResourceManager.GetString("M_DOC_DATE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to USER_OPER_DATE.
        /// </summary>
        public static string USER_OPER_DATE__Title {
            get {
                return ResourceManager.GetString("USER_OPER_DATE__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to USER_OPER_DATE.
        /// </summary>
        public static string USER_OPER_DATE__Comment
        {
            get 
            {
                return ResourceManager.GetString("USER_OPER_DATE__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_operdate.
        /// </summary>
        public static string m_message_operdate__Title {
            get {
                return ResourceManager.GetString("m_message_operdate__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_operdate.
        /// </summary>
        public static string m_message_operdate__Comment
        {
            get 
            {
                return ResourceManager.GetString("m_message_operdate__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_createdate.
        /// </summary>
        public static string m_message_createdate__Title {
            get {
                return ResourceManager.GetString("m_message_createdate__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_createdate.
        /// </summary>
        public static string m_message_createdate__Comment
        {
            get 
            {
                return ResourceManager.GetString("m_message_createdate__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_authdate.
        /// </summary>
        public static string m_message_authdate__Title {
            get {
                return ResourceManager.GetString("m_message_authdate__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_authdate.
        /// </summary>
        public static string m_message_authdate__Comment
        {
            get 
            {
                return ResourceManager.GetString("m_message_authdate__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_referense.
        /// </summary>
        public static string m_message_referense__Title {
            get {
                return ResourceManager.GetString("m_message_referense__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_referense.
        /// </summary>
        public static string m_message_referense__Comment
        {
            get 
            {
                return ResourceManager.GetString("m_message_referense__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_type.
        /// </summary>
        public static string m_message_type__Title {
            get {
                return ResourceManager.GetString("m_message_type__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_type.
        /// </summary>
        public static string m_message_type__Comment
        {
            get 
            {
                return ResourceManager.GetString("m_message_type__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_subtype.
        /// </summary>
        public static string m_message_subtype__Title {
            get {
                return ResourceManager.GetString("m_message_subtype__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_subtype.
        /// </summary>
        public static string m_message_subtype__Comment
        {
            get 
            {
                return ResourceManager.GetString("m_message_subtype__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_owner.
        /// </summary>
        public static string m_message_owner__Title {
            get {
                return ResourceManager.GetString("m_message_owner__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_owner.
        /// </summary>
        public static string m_message_owner__Comment
        {
            get 
            {
                return ResourceManager.GetString("m_message_owner__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_auth.
        /// </summary>
        public static string m_message_auth__Title {
            get {
                return ResourceManager.GetString("m_message_auth__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_auth.
        /// </summary>
        public static string m_message_auth__Comment
        {
            get 
            {
                return ResourceManager.GetString("m_message_auth__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to message_systemcomment.
        /// </summary>
        public static string message_systemcomment__Title {
            get {
                return ResourceManager.GetString("message_systemcomment__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to message_systemcomment.
        /// </summary>
        public static string message_systemcomment__Comment
        {
            get 
            {
                return ResourceManager.GetString("message_systemcomment__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_rcx.
        /// </summary>
        public static string m_message_rcx__Title {
            get {
                return ResourceManager.GetString("m_message_rcx__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to m_message_rcx.
        /// </summary>
        public static string m_message_rcx__Comment
        {
            get 
            {
                return ResourceManager.GetString("m_message_rcx__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Да.
        /// </summary>
        public static string m_message_rcx__TrueText
        {
            get 
            {
                return ResourceManager.GetString("m_message_rcx__TrueText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Нет.
        /// </summary>
        public static string m_message_rcx__FalseText
        {
            get 
            {
                return ResourceManager.GetString("m_message_rcx__FalseText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to messageDocumentReferense.
        /// </summary>
        public static string messageDocumentReferense__Title {
            get {
                return ResourceManager.GetString("messageDocumentReferense__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to messageDocumentReferense.
        /// </summary>
        public static string messageDocumentReferense__Comment
        {
            get 
            {
                return ResourceManager.GetString("messageDocumentReferense__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to psstScreening.
        /// </summary>
        public static string psstScreening__Title {
            get {
                return ResourceManager.GetString("psstScreening__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to psstScreening.
        /// </summary>
        public static string psstScreening__Comment
        {
            get 
            {
                return ResourceManager.GetString("psstScreening__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to operDate.
        /// </summary>
        public static string operDate__Title {
            get {
                return ResourceManager.GetString("operDate__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to operDate.
        /// </summary>
        public static string operDate__Comment
        {
            get 
            {
                return ResourceManager.GetString("operDate__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to rcxREF.
        /// </summary>
        public static string rcxREF__Title {
            get {
                return ResourceManager.GetString("rcxREF__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to rcxREF.
        /// </summary>
        public static string rcxREF__Comment
        {
            get 
            {
                return ResourceManager.GetString("rcxREF__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to restApiId.
        /// </summary>
        public static string restApiId__Title {
            get {
                return ResourceManager.GetString("restApiId__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to restApiId.
        /// </summary>
        public static string restApiId__Comment
        {
            get 
            {
                return ResourceManager.GetString("restApiId__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to psstId.
        /// </summary>
        public static string psstId__Title {
            get {
                return ResourceManager.GetString("psstId__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to psstId.
        /// </summary>
        public static string psstId__Comment
        {
            get 
            {
                return ResourceManager.GetString("psstId__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to externalSystemId.
        /// </summary>
        public static string externalSystemId__Title {
            get {
                return ResourceManager.GetString("externalSystemId__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to externalSystemId.
        /// </summary>
        public static string externalSystemId__Comment
        {
            get 
            {
                return ResourceManager.GetString("externalSystemId__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to externalState.
        /// </summary>
        public static string externalState__Title {
            get {
                return ResourceManager.GetString("externalState__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to externalState.
        /// </summary>
        public static string externalState__Comment
        {
            get 
            {
                return ResourceManager.GetString("externalState__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to rcxUNIQUEREF.
        /// </summary>
        public static string rcxUNIQUEREF__Title {
            get {
                return ResourceManager.GetString("rcxUNIQUEREF__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to rcxUNIQUEREF.
        /// </summary>
        public static string rcxUNIQUEREF__Comment
        {
            get 
            {
                return ResourceManager.GetString("rcxUNIQUEREF__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to reconciliationExported.
        /// </summary>
        public static string reconciliationExported__Title {
            get {
                return ResourceManager.GetString("reconciliationExported__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to reconciliationExported.
        /// </summary>
        public static string reconciliationExported__Comment
        {
            get 
            {
                return ResourceManager.GetString("reconciliationExported__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Да.
        /// </summary>
        public static string reconciliationExported__TrueText
        {
            get 
            {
                return ResourceManager.GetString("reconciliationExported__TrueText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Нет.
        /// </summary>
        public static string reconciliationExported__FalseText
        {
            get 
            {
                return ResourceManager.GetString("reconciliationExported__FalseText", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to maker.
        /// </summary>
        public static string maker__Title {
            get {
                return ResourceManager.GetString("maker__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to maker.
        /// </summary>
        public static string maker__Comment
        {
            get 
            {
                return ResourceManager.GetString("maker__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to checker.
        /// </summary>
        public static string checker__Title {
            get {
                return ResourceManager.GetString("checker__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to checker.
        /// </summary>
        public static string checker__Comment
        {
            get 
            {
                return ResourceManager.GetString("checker__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to isRtrn.
        /// </summary>
        public static string isRtrn__Title {
            get {
                return ResourceManager.GetString("isRtrn__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to isRtrn.
        /// </summary>
        public static string isRtrn__Comment
        {
            get 
            {
                return ResourceManager.GetString("isRtrn__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to rtrnOrgId.
        /// </summary>
        public static string rtrnOrgId__Title {
            get {
                return ResourceManager.GetString("rtrnOrgId__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to rtrnOrgId.
        /// </summary>
        public static string rtrnOrgId__Comment
        {
            get 
            {
                return ResourceManager.GetString("rtrnOrgId__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to rtrnOrgSts.
        /// </summary>
        public static string rtrnOrgSts__Title {
            get {
                return ResourceManager.GetString("rtrnOrgSts__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to rtrnOrgSts.
        /// </summary>
        public static string rtrnOrgSts__Comment
        {
            get 
            {
                return ResourceManager.GetString("rtrnOrgSts__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение TBL.
        /// </summary>
        public static string MT_Messages_TBL__VMTitle {
            get {
                return ResourceManager.GetString("MT_Messages_TBL__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение TBL.
        /// </summary>
        public static string MT_Messages_TBL__VMComment
        {
            get 
            {
                return ResourceManager.GetString("MT_Messages_TBL__VMComment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение TBL.
        /// </summary>
        public static string MT_Messages_TBLMinimal__VMTitle {
            get {
                return ResourceManager.GetString("MT_Messages_TBLMinimal__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Сообщение TBL.
        /// </summary>
        public static string MT_Messages_TBLMinimal__VMComment
        {
            get 
            {
                return ResourceManager.GetString("MT_Messages_TBLMinimal__VMComment", resourceCulture);
            }
        }
    }
}