//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanksGateDataModel.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BanksGateDataModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не определен курс валюты {0} на дату {1:d}.
        /// </summary>
        public static string CurrencyRateNotExists {
            get {
                return ResourceManager.GetString("CurrencyRateNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись валюты не найдена.
        /// </summary>
        public static string CurrencyRowNotExists {
            get {
                return ResourceManager.GetString("CurrencyRowNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для каждого типа оповещения может быть только один шаблон оповещения Outlook.
        /// </summary>
        public static string DIC_OutlookTemplates_UNDX_refOutlookTemplateType {
            get {
                return ResourceManager.GetString("DIC_OutlookTemplates_UNDX_refOutlookTemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус договора должен быть утвержденный и стоять отметка Checker-а..
        /// </summary>
        public static string FilterByApprovedAndSigned {
            get {
                return ResourceManager.GetString("FilterByApprovedAndSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вид договора не задан, необходимо внести корректировку в договор и утвердить..
        /// </summary>
        public static string FilterByExcludeAttrNotSet {
            get {
                return ResourceManager.GetString("FilterByExcludeAttrNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус договора не должен быть закрытый..
        /// </summary>
        public static string FilterByExcludeClosed {
            get {
                return ResourceManager.GetString("FilterByExcludeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправка документов на скрининг была только что выполнена другим пользователем, повторите попытку..
        /// </summary>
        public static string MCC_ScreeningDocument_UNDX_refContract_SendDate {
            get {
                return ResourceManager.GetString("MCC_ScreeningDocument_UNDX_refContract_SendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправка документов на скрининг была только что выполнена другим пользователем, повторите попытку..
        /// </summary>
        public static string MCC_ScreeningDocumentLinks_UNDX_refDocument_refScreeningDocument {
            get {
                return ResourceManager.GetString("MCC_ScreeningDocumentLinks_UNDX_refDocument_refScreeningDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет документа.
        /// </summary>
        public static string NoDocument {
            get {
                return ResourceManager.GetString("NoDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не подписано.
        /// </summary>
        public static string NotSigned {
            get {
                return ResourceManager.GetString("NotSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на №п/п должен быть уникальным.
        /// </summary>
        public static string Registry_UNDX_Number {
            get {
                return ResourceManager.GetString("Registry_UNDX_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учетный номер ВД должен быть уникальным.
        /// </summary>
        public static string Registry_UNDX_UNC {
            get {
                return ResourceManager.GetString("Registry_UNDX_UNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправьте запрос позже.
        /// </summary>
        public static string TryLater {
            get {
                return ResourceManager.GetString("TryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле BaseID клиента должно быть уникальным.
        /// </summary>
        public static string UNDX_BaseId {
            get {
                return ResourceManager.GetString("UNDX_BaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле код должно быть уникальным.
        /// </summary>
        public static string UNDX_Code {
            get {
                return ResourceManager.GetString("UNDX_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле 2х-значный цифровой код должно быть уникальным.
        /// </summary>
        public static string UNDX_Code2Char {
            get {
                return ResourceManager.GetString("UNDX_Code2Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле 3х-значный буквенный код должно быть уникальным.
        /// </summary>
        public static string UNDX_Code3Char {
            get {
                return ResourceManager.GetString("UNDX_Code3Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле 3х-значный цифровой код должно быть уникальным.
        /// </summary>
        public static string UNDX_Code3Int {
            get {
                return ResourceManager.GetString("UNDX_Code3Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле цифровой код должно быть уникальным.
        /// </summary>
        public static string UNDX_CodeInt {
            get {
                return ResourceManager.GetString("UNDX_CodeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В календарь на указанную дату уже заведена информация, обновите данные на странице..
        /// </summary>
        public static string UNDX_HolidayDate {
            get {
                return ResourceManager.GetString("UNDX_HolidayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email адрес не может повторятся в контактах у клиента.
        /// </summary>
        public static string UNDX_refClient_Email {
            get {
                return ResourceManager.GetString("UNDX_refClient_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение полей КНП и Тип платежа не могут повторятся.
        /// </summary>
        public static string UNDX_refKNP_PaymentDirection {
            get {
                return ResourceManager.GetString("UNDX_refKNP_PaymentDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение полей КНП, Тип платежа и Резидент не могут повторятся.
        /// </summary>
        public static string UNDX_refKNP_PaymentDirection_Resident {
            get {
                return ResourceManager.GetString("UNDX_refKNP_PaymentDirection_Resident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
