//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxInterface_TI.Areas.TI.GeneratedResources {
    using global::System;
    using global::System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TaxPaymentsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal TaxPaymentsResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaxInterface_TI.Areas.TI.GeneratedResources.TaxPaymentsResources", typeof(TaxPaymentsResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string TaxPayments__Title {
            get {
                return ResourceManager.GetString("TaxPayments__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string TaxPayments__Comment
        {
            get 
            {
                return ResourceManager.GetString("TaxPayments__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string TaxPayments__DescriptionRtf
        {
            get 
            {
                return ResourceManager.GetString("TaxPayments__DescriptionRtf", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Идентификатор.
        /// </summary>
        public static string id__Title {
            get {
                return ResourceManager.GetString("id__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Идентификатор.
        /// </summary>
        public static string id__Comment
        {
            get 
            {
                return ResourceManager.GetString("id__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Наименование.
        /// </summary>
        public static string Name__Title {
            get {
                return ResourceManager.GetString("Name__Title", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to Наименование.
        /// </summary>
        public static string Name__Comment
        {
            get 
            {
                return ResourceManager.GetString("Name__Comment", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string TaxPayments__VMTitle {
            get {
                return ResourceManager.GetString("TaxPayments__VMTitle", resourceCulture);
            }
        }
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string TaxPayments__VMComment
        {
            get 
            {
                return ResourceManager.GetString("TaxPayments__VMComment", resourceCulture);
            }
        }
    }
}